name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup winget
      uses: Cyberboss/install-winget@v1

    - name: Install build tools
      run: |
        winget install Microsoft.VisualStudio.BuildTools
        winget install -e --id Kitware.CMake --accept-source-agreements --accept-package-agreements --silent
        winget install -e --id Ninja-build.Ninja --accept-source-agreements --accept-package-agreements --silent
        winget install --id Git.Git -e --source winget --accept-source-agreements --accept-package-agreements --silent

    - name: Run build script
      run: |
        .github/scripts/build-windows.ps1

    - name: Run tests
      run: |
        cd out/build/x64-debug/loc.tests
        ./loc.tests
