name: Windows Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ninja
      id: setup-ninja
      uses: ashutoshvarma/setup-ninja@master

    - name: Add Ninja to PATH
      run: |
        echo "${{ steps.setup-ninja.outpus.ninja-path }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v2

    - name: Run build script
      run: |
        .github/scripts/build-windows.ps1

    - name: Run tests
      run: |
        cd out/build/x64-debug/loc.tests
        ./loc.tests
