name: Windows Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ninja
      run: choco install ninja --confirm

    - name: Install Visual Studio 2022 Build Tools
      run: |
        choco install visualstudio2022buildtools --confirm
        choco install visualstudio2022-workload-vctools --confirm
        choco install vswhere --confirm

    - name: Set up Visual Studio environment
      run: |
        $vsInstallPath = &vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
        & "$vsInstallPath\VC\Auxiliary\Build\vcvarsall.bat" x64

    - name: Run build script
      run: |
        .github/scripts/build-windows.ps1

    - name: Run tests
      run: |
        cd out/build/x64-debug/loc.tests
        ./loc.tests
