name: Windows Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ninja
      run: choco install ninja --confirm

    - name: Install Visual Studio 2022 Build Tools
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with: 
        arch: x64

    - name: Run build script
      run: |
        .github/scripts/build-windows.ps1

    - name: Run tests
      run: |
        cd out/build/x64-debug/loc.tests
        ./loc.tests
