name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build script
      run: .github/scripts/build-linux.sh

    - name: Run tests
      run: |
        cd out/build/linux-debug/loc.tests
        ./loc.tests
