name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        cd ..
        export VCPKG_ROOT="$(pwd)/vcpkg"
        export PATH=$VCPKG_ROOT:$PATH

    - name: Build and run tests
      run: |
        mkdir -p build
        cd build
        cmake --preset=linux-debug ..
        make
        cd loc.tests
        ./loc.tests
