name: Run test suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ninja
      run: choco install ninja --confirm

    - name: Install Visual Studio 2022 Build Tools
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with: 
        arch: x64

    - name: Run build script
      run: |
        .github/scripts/build-windows.ps1

    - name: Run tests
      run: |
        cd out/build/x64-release
        ninja
        cd loc.tests
        ./loc.tests
        cd ../loc
        ./loc --help

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Run build script
      run: |
        chmod +x .github/scripts/build-linux.sh
        .github/scripts/build-linux.sh

    - name: Run tests
      run: |
        cd out/build/linux-release/loc.tests
        ./loc.tests
        cd ../loc
        ./loc --help
