name: Build and Upload Release

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Ninja
      run: choco install ninja --confirm

    - name: Install Visual Studio 2022 Build Tools
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    
    - name: Run build script
      run: |
        .github/scripts/build-windows.ps1

    - name: Run tests
      run: |
        cd out/build/x64-release
        ninja
        cd loc.tests
        ./loc.tests
        cd ../../../..

    - name: Create zip file
      run: powershell Compress-Archive -Path out\build\x64-release\loc\loc.exe -DestinationPath out\build\x64-release\loc-windows-x64.zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: out/build/x64-release/loc/loc-windows-x64.zip
        asset_name: loc-windows-x64.zip
        asset_content_type: application/zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Run build script
      run: |
        chmod +x .github/scripts/build-linux.sh
        .github/scripts/build-linux.sh
    
    - name: Run tests
      run: |
        cd out/build/linux-release/loc.tests
        ./loc.tests
        cd ../../../..

    - name: Create zip file
      run: zip -j out/build/linux-release/loc-linux-x64.zip out/build/linux-release/loc/loc

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: out/build/linux-release/loc-linux-x64.zip
        asset_name: loc-linux-x64.zip
        asset_content_type: application/zip
